/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-10 -O2 -fdebug-prefix-map=/build/yosys-0DEyT5/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module RDM(CLK, IN_Data, OUT_Data);
  input CLK;
  input IN_Data;
  output OUT_Data;
  DFF _0_ (
    .C(CLK),
    .D(IN_Data),
    .Q(OUT_Data)
  );
endmodule
