/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-10 -O2 -fdebug-prefix-map=/build/yosys-0DEyT5/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module serialparalelo(CLOCK, ENABLE, IS, OP);
  wire [4:0] _000_;
  wire [9:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire [31:0] _088_;
  wire [1:0] _089_;
  wire _090_;
  wire [1:0] _091_;
  wire _092_;
  wire [4:0] _093_;
  wire _094_;
  wire _095_;
  wire [4:0] _096_;
  wire [31:0] _097_;
  wire _098_;
  input CLOCK;
  input ENABLE;
  input IS;
  output [9:0] OP;
  wire [4:0] contador;
  wire [9:0] temp;
  NOT _099_ (
    .A(_018_),
    .Y(_019_)
  );
  NOT _100_ (
    .A(_059_),
    .Y(_020_)
  );
  NAND _101_ (
    .A(_020_),
    .B(_019_),
    .Y(_021_)
  );
  NOT _102_ (
    .A(_004_),
    .Y(_022_)
  );
  NOT _103_ (
    .A(_002_),
    .Y(_023_)
  );
  NOR _104_ (
    .A(_003_),
    .B(_023_),
    .Y(_024_)
  );
  NAND _105_ (
    .A(_024_),
    .B(_022_),
    .Y(_026_)
  );
  NOR _106_ (
    .A(_026_),
    .B(_021_),
    .Y(_028_)
  );
  NAND _107_ (
    .A(_028_),
    .B(_005_),
    .Y(_030_)
  );
  NOT _108_ (
    .A(_003_),
    .Y(_032_)
  );
  NAND _109_ (
    .A(_032_),
    .B(_002_),
    .Y(_034_)
  );
  NOR _110_ (
    .A(_034_),
    .B(_021_),
    .Y(_035_)
  );
  NAND _111_ (
    .A(_035_),
    .B(_022_),
    .Y(_036_)
  );
  NAND _112_ (
    .A(_036_),
    .B(_038_),
    .Y(_037_)
  );
  NAND _113_ (
    .A(_037_),
    .B(_030_),
    .Y(_006_)
  );
  NAND _114_ (
    .A(_036_),
    .B(_040_),
    .Y(_039_)
  );
  NAND _115_ (
    .A(_039_),
    .B(_030_),
    .Y(_007_)
  );
  NAND _116_ (
    .A(_036_),
    .B(_041_),
    .Y(_042_)
  );
  NAND _117_ (
    .A(_042_),
    .B(_030_),
    .Y(_008_)
  );
  NAND _118_ (
    .A(_036_),
    .B(_043_),
    .Y(_045_)
  );
  NAND _119_ (
    .A(_045_),
    .B(_030_),
    .Y(_009_)
  );
  NAND _120_ (
    .A(_036_),
    .B(_044_),
    .Y(_048_)
  );
  NAND _121_ (
    .A(_048_),
    .B(_030_),
    .Y(_010_)
  );
  NAND _122_ (
    .A(_036_),
    .B(_046_),
    .Y(_051_)
  );
  NAND _123_ (
    .A(_051_),
    .B(_030_),
    .Y(_011_)
  );
  NAND _124_ (
    .A(_036_),
    .B(_047_),
    .Y(_053_)
  );
  NAND _125_ (
    .A(_053_),
    .B(_030_),
    .Y(_012_)
  );
  NAND _126_ (
    .A(_036_),
    .B(_049_),
    .Y(_054_)
  );
  NAND _127_ (
    .A(_054_),
    .B(_030_),
    .Y(_013_)
  );
  NAND _128_ (
    .A(_036_),
    .B(_050_),
    .Y(_055_)
  );
  NAND _129_ (
    .A(_055_),
    .B(_030_),
    .Y(_014_)
  );
  NAND _130_ (
    .A(_036_),
    .B(_052_),
    .Y(_056_)
  );
  NAND _131_ (
    .A(_056_),
    .B(_030_),
    .Y(_015_)
  );
  NOT _132_ (
    .A(_005_),
    .Y(_057_)
  );
  NOT _133_ (
    .A(_016_),
    .Y(_058_)
  );
  NOR _134_ (
    .A(_058_),
    .B(_057_),
    .Y(_017_)
  );
  NOR _135_ (
    .A(_058_),
    .B(_002_),
    .Y(_025_)
  );
  NOR _136_ (
    .A(_032_),
    .B(_002_),
    .Y(_060_)
  );
  NOR _137_ (
    .A(_060_),
    .B(_024_),
    .Y(_061_)
  );
  NOR _138_ (
    .A(_021_),
    .B(_022_),
    .Y(_062_)
  );
  NAND _139_ (
    .A(_062_),
    .B(_060_),
    .Y(_063_)
  );
  NAND _140_ (
    .A(_063_),
    .B(_016_),
    .Y(_064_)
  );
  NOR _141_ (
    .A(_064_),
    .B(_061_),
    .Y(_027_)
  );
  NAND _142_ (
    .A(_003_),
    .B(_002_),
    .Y(_065_)
  );
  NAND _143_ (
    .A(_065_),
    .B(_019_),
    .Y(_066_)
  );
  NOR _144_ (
    .A(_032_),
    .B(_023_),
    .Y(_067_)
  );
  NAND _145_ (
    .A(_067_),
    .B(_018_),
    .Y(_068_)
  );
  NAND _146_ (
    .A(_068_),
    .B(_066_),
    .Y(_069_)
  );
  NOR _147_ (
    .A(_069_),
    .B(_064_),
    .Y(_029_)
  );
  NOR _148_ (
    .A(_065_),
    .B(_019_),
    .Y(_070_)
  );
  NAND _149_ (
    .A(_070_),
    .B(_004_),
    .Y(_071_)
  );
  NAND _150_ (
    .A(_068_),
    .B(_022_),
    .Y(_072_)
  );
  NAND _151_ (
    .A(_072_),
    .B(_071_),
    .Y(_073_)
  );
  NOR _152_ (
    .A(_073_),
    .B(_064_),
    .Y(_031_)
  );
  NOR _153_ (
    .A(_068_),
    .B(_022_),
    .Y(_074_)
  );
  NOR _154_ (
    .A(_074_),
    .B(_020_),
    .Y(_075_)
  );
  NOR _155_ (
    .A(_071_),
    .B(_059_),
    .Y(_076_)
  );
  NOR _156_ (
    .A(_076_),
    .B(_075_),
    .Y(_077_)
  );
  NOR _157_ (
    .A(_077_),
    .B(_064_),
    .Y(_033_)
  );
  DFF _158_ (
    .C(CLOCK),
    .D(_001_[9]),
    .Q(IS)
  );
  DFF _159_ (
    .C(CLOCK),
    .D(_000_[0]),
    .Q(contador[0])
  );
  DFF _160_ (
    .C(CLOCK),
    .D(_000_[1]),
    .Q(contador[1])
  );
  DFF _161_ (
    .C(CLOCK),
    .D(_000_[2]),
    .Q(contador[2])
  );
  DFF _162_ (
    .C(CLOCK),
    .D(_000_[3]),
    .Q(contador[3])
  );
  DFF _163_ (
    .C(CLOCK),
    .D(_000_[4]),
    .Q(contador[4])
  );
  assign temp = { IS, IS, IS, IS, IS, IS, IS, IS, IS, IS };
  assign _078_ = OP[0];
  assign _079_ = OP[1];
  assign _080_ = OP[2];
  assign _081_ = OP[3];
  assign _082_ = OP[4];
  assign _083_ = OP[5];
  assign _084_ = OP[6];
  assign _085_ = OP[7];
  assign _086_ = OP[8];
  assign _087_ = OP[9];
  assign _002_ = contador[0];
  assign _018_ = contador[2];
  assign _059_ = contador[4];
  assign _003_ = contador[1];
  assign _004_ = contador[3];
  assign _005_ = IS;
  assign OP[0] = _006_;
  assign OP[1] = _007_;
  assign OP[2] = _008_;
  assign OP[3] = _009_;
  assign OP[4] = _010_;
  assign OP[5] = _011_;
  assign OP[6] = _012_;
  assign OP[7] = _013_;
  assign OP[8] = _014_;
  assign OP[9] = _015_;
  assign _016_ = ENABLE;
  assign _001_[9] = _017_;
  assign _000_[0] = _025_;
  assign _000_[1] = _027_;
  assign _000_[2] = _029_;
  assign _000_[3] = _031_;
  assign _000_[4] = _033_;
  assign _038_ = _078_;
  assign _040_ = _079_;
  assign _041_ = _080_;
  assign _043_ = _081_;
  assign _044_ = _082_;
  assign _046_ = _083_;
  assign _047_ = _084_;
  assign _049_ = _085_;
  assign _050_ = _086_;
  assign _052_ = _087_;
endmodule
